### ISSUE TITLE
What is the meaning of the parameter 'detection_rate'? 

### ISSUE THREAD

**Issue by YuanShunJie1** [WWlnZSBMaXU/Triggerless#1]
```
    parser.add_argument('--detection_rate',
                        help="``--detection_rate 0.8'' means that there is a 80 percent probability of detecting the trigger;",
                        type=float,
                        default=0.8)
```
I have no idea about this parameter. Does the detection means that replace the embeddings with random embddeings?                                    
` emb[attacker][i] = torch.randn_like(emb[attacker][i]) * emb[attacker].std(dim=0).mean()`

By the way this paper and work here is a great job in VFL, and I want to cite it in my work, but I cannot find it on Google Scholar.

**Comment by WWlnZSBMaXU** [comment]
In our paper, we evaluate the robustness of our method using four defenses, one of which is `detection`. When the active party employs this defense, it replaces the malicious embeddings. We simulate the `detection` defense and use this parameter to control the defense level.

Our paper is currently under review, and we have ongoing work based on this paper. Therefore, it may not be convenient to publish it on arXiv at this time. I will contact you once our paper is published. Thank you.
