### ISSUE TITLE
About VILLAIN attack

### ISSUE THREAD

**Issue by YuanShunJie1** [WWlnZSBMaXU/Triggerless#2]
I have reproduced your code on VILLAIN backdoor attacks using the MNIST dataset, but the attack's performance is poor. Could you share your experimental results about VILLAIN? The results of VILLAIN on MNIST is listed as bellow:

```
============== Backdoor ==============
Average LIA Attack Accuracy of Passive 0 (each epoch): 70.01%
Average LIA Attack Accuracy of Passive 1 (each epoch): 67.57%
Attacker 0's Manipulated Backdoor Attack Accuracy: 2/1398 (0.14%)
Attacker 0's Real Backdoor Attack Accuracy: 0/1126 (0.00%)
```

**Comment by WWlnZSBMaXU** [comment]
We got similar experimental results to yours and presented them in our paper with explanations. We are glad to share it with you, but as you know, our paper is under review and our ongoing work is based on it. So you can wait for the publication or just follow the code.
